FORMATO CSV
==

In [ ]:
import pandas as pd
dat_csv = pd.read_csv('/content/sample_data/empleados.csv', encoding = "ISO-8859-1")
dat_csv

   id   Nombre Genero  Sueldo
0   1     Juan      m   10000
1   2    Ramón      m   20000
2   3     Anna      f   10500
3   4  Julieta      f   13000
4   5    Pablo      m   30000
5   6    Pedro      m   10500
6   7     Gaby      f   11000
7   8  Cecilia      f   27000

>Si queremos que en lugar de todos los datos, se restrinja la salida a las primeras cinco filas, podemos utilizar el método head().

In [ ]:
dat_csv.head()

   id   Nombre Genero  Sueldo
0   1     Juan      m   10000
1   2    Ramón      m   20000
2   3     Anna      f   10500
3   4  Julieta      f   13000
4   5    Pablo      m   30000

>En los dos casos anteriores, aparecen los elementos de la primera fila como los nombres de las columnas de datos, si no quisiéramos este comportamiento podemos agregar el atributo header = None, de la siguiente manera:

In [ ]:
dat_csv = pd.read_csv('datos/empleados.csv', encoding = "ISO-8859-1", header = None)
dat_csv

>Si quisiéramos que tomar una determinada línea como cabecera, debemos asignarle al parámetro header el número de fila correspondiente, en el siguiente ejemplo se toma la línea 3 como cabecera:

In [ ]:
dat_csv = pd.read_csv('datos/empleados.csv', encoding = "ISO-8859-1", header = 3)
dat_csv

>Por defecto, read_csv asigna un índice numérico predeterminado que comienza con cero al leer los datos. Sin embargo, es posible alterar este comportamiento pasando el nombre de la columna que utilizaremos como índice. A continuación se dejara la columna id como índice de la tabla:

In [ ]:
dat_csv = pd.read_csv('/content/sample_data/empleados.csv', encoding = "ISO-8859-1", index_col='id')
dat_csv

     Nombre Genero  Sueldo
id
1      Juan      m   10000
2     Ramón      m   20000
3      Anna      f   10500
4   Julieta      f   13000
5     Pablo      m   30000
6     Pedro      m   10500
7      Gaby      f   11000
8   Cecilia      f   27000

>En el caso de que queramos restringir la tabla a algunas columnas específicas, podemos realizarlo con el parámetro __usecols__ indicando en una lista las columnas seleccionadas.

In [ ]:
dat_csv  = pd.read_csv('/content/sample_data/empleados.csv', encoding = "ISO-8859-1", usecols=['Nombre', 'Sueldo'])
dat_csv.head()

    Nombre  Sueldo
0     Juan   10000
1    Ramón   20000
2     Anna   10500
3  Julieta   13000
4    Pablo   30000

>Si queremos eliminar una fila en particular, podemos utilizar el parámetro skiprows, en el siguiente caso se eliminan las filas 1 y 4:

In [ ]:
dat_csv  = pd.read_csv('datos/empleados.csv', encoding = "ISO-8859-1", skiprows = [1,4])
dat_csv

>Para presentar un número dado de filas desde el inicio, podemos utilizar el parámetro nrows, en el siguiente ejemplo se presentan las primeras tres filas de datos.

In [ ]:
dat_csv  = pd.read_csv('datos/empleados.csv', encoding = "ISO-8859-1",  nrows=3)
dat_csv

>Para seleccionar un rango específico de filas podemos utilizar el método query especificando los límites aplicables sobre una determinada columna:

In [ ]:
dat_csv  = pd.read_csv('datos/empleados.csv', encoding = "ISO-8859-1")
dat_csv.query('2 < id < 6')

>Para tratar con los datos de una columna, podemos recuperarlos dentro de una lista mediante el uso de un bucle for, y luego si es necesario convertir la lista en una array como se muestra a continuación:

In [ ]:
import pandas as pd
import numpy as np
dat_csv  = pd.read_csv('/content/sample_data/datos.csv', encoding = "ISO-8859-1")
datos_x = dat_csv.nombre
datos_y = dat_csv.genero
x = []
y = []
for i in dat_csv.nombre:
    x.append(i)
for j in dat_csv.genero:
    y.append(j)
print(x)
print(y)

x_array = np.array(x)
print(type(x_array))
print(x_array)

['Juan', 'Pedro', 'Marcelo', 'Anna']
['m', 'm', 'm', 'f']
<class 'numpy.ndarray'>
['Juan' 'Pedro' 'Marcelo' 'Anna']

FORMATO EXCEL
==

>En el caso de trabajar directamente con un archivo de Excel, podemos utilizar el método __read_excel()__

In [ ]:
import pandas as pd
dat_excel  = pd.read_excel('/content/sample_data/empleados.xlsx', engine='openpyxl')
dat_excel.head()

   ID          Nombre  Edad      Departamento  Salario
0   1      Juan Pérez    28            Ventas    50000
1   2     María López    34  Recursos Humanos    60000
2   3    Carlos Gómez    45                IT    75000
3   4      Ana Torres    29         Marketing    52000
4   5  Luis Fernández    40          Finanzas    68000

FORMATO JSON
==

In [ ]:
import pandas as pd
movies_json = pd.read_json('/content/sample_data/anscombe.json')
movies_json.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

FORMATO HTML
==

In [ ]:
import pandas as pd
pd.read_html('/content/sample_data/empleados.html')

[   ID        Nombre           Cargo      Departamento Salario
 0   1    Juan Pérez        Analista                IT   $1200
 1   2   María Gómez         Gerente  Recursos Humanos   $2500
 2   3  Carlos López       Diseñador         Marketing   $1500
 3   4    Ana Torres  Desarrolladora                IT   $1800]

BASE DE DATOS
==

In [ ]:
import pandas as pd
import sqlite3
conn = sqlite3.connect("/content/sample_data/empleados.db")
df = pd.read_sql_query("SELECT * FROM empleados;", conn)
df.head()

   id          nombre            cargo      departamento  salario
0   1      Juan Pérez         Analista                IT   1200.0
1   2     María Gómez          Gerente  Recursos Humanos   2500.0
2   3    Carlos López        Diseñador         Marketing   1500.0
3   4      Ana Torres   Desarrolladora                IT   1800.0
4   5  Luis Fernández  Soporte Técnico                IT   1100.0

FORMATO XML
==

In [ ]:
import xml.etree.cElementTree as et
parsed_xml = et.parse("datos/datos.xml")


import pandas as pd

def obtenerValorDeNodo(node):
    return node.text if node is not None else None


def main():
    parsed_xml = et.parse("datos/datos.xml")
    dfcols = ['nombre', 'email', 'telefono', 'calle']
    df_xml = pd.DataFrame(columns=dfcols)

    for node in parsed_xml.getroot():
        nombre = node.attrib.get('nombre')
        email = node.find('email')
        telefono = node.find('telefono')
        calle = node.find('direccion/calle')

        df_xml = df_xml.append(  pd.Series([nombre, obtenerValorDeNodo(email),
                 obtenerValorDeNodo(telefono),  obtenerValorDeNodo(calle)],
                 index=dfcols), ignore_index=True)
    print(df_xml)

main()